apiVersion: v1
kind: Namespace
metadata:
  name: hiroworksteal1
  labels:
    environment: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: hiroworksteal1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80